name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run PyInstaller
        run: python build_modern.py

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zilean
          path: dist/Zilean.exe  # Note: keeping the same name

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Modern Zilean - Floating Jira Time Tracker
            - Modern PySide6 interface
            - Floating widget design
            - Configurable colors
            - Better performance
          files: dist/Zilean.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
